"""initial tables

Revision ID: 0001
Revises:
Create Date: 2026-09-29 18:39:18.227020
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wa_number", sa.String(length=32), nullable=False),
        sa.Column("wa_profile_name", sa.String(length=120), nullable=True),
        sa.Column("contact_name", sa.String(length=60), nullable=True),
        sa.Column("relationship", sa.String(length=16), nullable=True),
        sa.Column("language", sa.String(length=4), nullable=False),
        sa.Column("consent_at", sa.DateTime(), nullable=True),
        sa.Column("rate_limited_until", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wa_number"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("collected", sa.JSON(), nullable=False),
        sa.Column("student_key", sa.String(length=80), nullable=False),
        sa.Column("close_reason", sa.String(length=24), nullable=True),
        sa.Column("handoff_reason", sa.String(length=24), nullable=True),
        sa.Column("handoff_at", sa.DateTime(), nullable=True),
        sa.Column("handoff_id", sa.String(length=24), nullable=True),
        sa.Column("misunderstand_streak", sa.Integer(), nullable=False),
        sa.Column("minor_alone", sa.Boolean(), nullable=False),
        sa.Column("consent_by_minor", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("lead_id", sa.String(length=24), nullable=True),
        sa.Column("first_inbound_at", sa.DateTime(), nullable=True),
        sa.Column("last_inbound_at", sa.DateTime(), nullable=True),
        sa.Column("last_outbound_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "uq_active_conversation",
            ["contact_id", "student_key"],
            unique=True,
            sqlite_where=sa.text(
                "state IN ('awaiting_consent', 'in_progress', 'confirming', 'stalled', 'handed_over')"
            ),
            postgresql_where=sa.text(
                "state IN ('awaiting_consent', 'in_progress', 'confirming', 'stalled', 'handed_over')"
            ),
        )

    op.create_table(
        "lead_outbox",
        sa.Column("lead_id", sa.String(length=24), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("row", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("lead_id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("wa_message_id", sa.String(length=128), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wa_message_id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_created_at"), ["created_at"], unique=False)

    op.create_table(
        "usage_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_events_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_events_created_at"))

    op.drop_table("usage_events")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_created_at"))

    op.drop_table("messages")
    op.drop_table("lead_outbox")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_active_conversation",
            sqlite_where=sa.text(
                "state IN ('awaiting_consent', 'in_progress', 'confirming', 'stalled', 'handed_over')"
            ),
            postgresql_where=sa.text(
                "state IN ('awaiting_consent', 'in_progress', 'confirming', 'stalled', 'handed_over')"
            ),
        )

    op.drop_table("conversations")
    op.drop_table("contacts")
    # ### end Alembic commands ###
